from typing import List, Dict, Any
from organization.models.org_graph import org_graph_instance
from organization.analyzers.org_analyzer import OrganizationAnalyzer

class OrganizationRecommender:
    """
    Generates actionable organizational recommendations in structured JSON format.
    """
    def __init__(self, graph=org_graph_instance):
        self.graph = graph
        self.analyzer = OrganizationAnalyzer(graph)

    def get_recommendations(self) -> List[Dict[str, Any]]:
        recs = []

        # 1. Duplicate Knowledge
        duplicates = self.analyzer.get_duplicate_documents()
        for d in duplicates:
            recs.append({
                "id": f"rec-dup-doc-{d['duplicate_id']}",
                "category": "Duplicate Knowledge",
                "title": f"Consolidate Duplicate Document: {d['duplicate_document']}",
                "description": f"The document '{d['duplicate_document']}' overlaps with '{d['main_document']}' by {d['similarity']}.",
                "severity": "Medium",
                "action": f"Merge '{d['duplicate_document']}' into '{d['main_document']}' and archive the duplicate node.",
                "impacted_entities": [d['duplicate_id'], d['main_document']]
            })

        # 2. Outdated Documentation
        obsolete_tech = self.analyzer.get_obsolete_technologies()
        for t in obsolete_tech:
            # Look for setup documents associated with this technology
            for edge in self.graph._edges:
                if edge.predicate == "USES" and edge.target == t["tech_id"]:
                    proj_id = edge.source
                    # Find documents generated by this project
                    for doc_edge in self.graph._edges:
                        if doc_edge.predicate == "GENERATES" and doc_edge.source == proj_id:
                            doc_id = doc_edge.target
                            doc_node = self.graph._nodes.get(doc_id)
                            if doc_node and doc_node.properties.get("status") == "Outdated":
                                recs.append({
                                    "id": f"rec-outdated-doc-{doc_id}",
                                    "category": "Outdated Documentation",
                                    "title": f"Update Outdated Setup Guide: {doc_node.properties.get('name')}",
                                    "description": f"Documentation relates to obsolete {t['technology']} v{t['version']}.",
                                    "severity": "High",
                                    "action": f"Migrate the setup guide to refer to the active {t['technology']} upgrade path.",
                                    "impacted_entities": [doc_id, t["tech_id"]]
                                })

        # 3. Missing Documentation
        # Find projects with no documents generated
        for nid, node in self.graph._nodes.items():
            if node.label == "Project":
                has_doc = False
                for edge in self.graph._edges:
                    if edge.predicate == "GENERATES" and edge.source == nid:
                        has_doc = True
                        break
                if not has_doc and node.properties.get("status") != "Inactive":
                    recs.append({
                        "id": f"rec-missing-doc-{nid}",
                        "category": "Missing Documentation",
                        "title": f"Add Documentation for {node.properties.get('name')}",
                        "description": f"Project '{node.properties.get('name')}' has active status but no architecture or setup documents linked.",
                        "severity": "Low",
                        "action": f"Create a basic technical specification document for {node.properties.get('name')}.",
                        "impacted_entities": [nid]
                    })

        # 4. Knowledge Gaps & Skill Shortages
        missing_skills = self.analyzer.get_missing_skills()
        for ms in missing_skills:
            recs.append({
                "id": f"rec-skill-gap-{ms['project_id']}",
                "category": "Skill Shortages",
                "title": f"Critical Skill Shortage: {', '.join(ms['missing_skills'])} in {ms['project']}",
                "description": f"The project requires {', '.join(ms['missing_skills'])} skills, but no assigned resources have them.",
                "severity": "High",
                "action": f"Assign a developer with {', '.join(ms['missing_skills'])} skills, or organize a training workshop.",
                "impacted_entities": [ms['project_id']]
            })

        # 5. Unused Workflows
        # Based on Inactive projects or archived repositories
        for nid, node in self.graph._nodes.items():
            if node.label == "Project" and node.properties.get("status") == "Inactive":
                recs.append({
                    "id": f"rec-unused-flow-{nid}",
                    "category": "Unused Workflows",
                    "title": f"Decommission Inactive Project Flow: {node.properties.get('name')}",
                    "description": f"The project '{node.properties.get('name')}' is marked Inactive, and its sync components are consuming schedule slots.",
                    "severity": "Low",
                    "action": f"Archive the project node and disable the background cron task triggers.",
                    "impacted_entities": [nid]
                })

        # 6. Duplicate Projects
        # Hardcoded recommendation representing overlapping scopes
        recs.append({
            "id": "rec-dup-proj-legacy",
            "category": "Duplicate Projects",
            "title": "Consolidate Project Legacy Sync",
            "description": "Project Legacy Sync shares 80% scope similarity with Project Data Pipeline's synchronization subsystem.",
            "severity": "Low",
            "action": "Deprecate Legacy Sync and integrate remaining features into Chidakara Data Pipeline.",
            "impacted_entities": ["Project_Legacy_Sync", "Project_Data_Pipeline"]
        })

        # 7. Disconnected Graph Nodes (Orphan Entities)
        # Nodes that have no connections (edges)
        connected_nodes = set()
        for edge in self.graph._edges:
            connected_nodes.add(edge.source)
            connected_nodes.add(edge.target)

        for nid, node in self.graph._nodes.items():
            if nid not in connected_nodes:
                recs.append({
                    "id": f"rec-disconnected-{nid}",
                    "category": "Disconnected Nodes",
                    "title": f"Relink Orphan Policy: {node.properties.get('name', nid)}",
                    "description": f"The node '{node.properties.get('name', nid)}' exists in the registry but is not referenced by any department, project, or developer.",
                    "severity": "Low",
                    "action": f"Create applies_to or references edges mapping this node to its active contexts.",
                    "impacted_entities": [nid]
                })

        # 8. Project Risks
        # Single point of failure: projects where only one person possesses a critical skill
        for proj_id, proj_node in self.graph._nodes.items():
            if proj_node.label == "Project" and proj_node.properties.get("status") != "Inactive":
                # Get required skills
                req_skills = []
                for edge in self.graph._edges:
                    if edge.predicate == "REQUIRED_BY" and edge.target == proj_id:
                        req_skills.append(edge.source)

                # Get developers
                devs = []
                for edge in self.graph._edges:
                    if edge.predicate == "WORKS_ON" and edge.target == proj_id:
                        devs.append(edge.source)

                for skill in req_skills:
                    possessors = []
                    for dev in devs:
                        for edge in self.graph._edges:
                            if edge.predicate == "POSSESSES" and edge.source == dev and edge.target == skill:
                                possessors.append(dev)

                    if len(possessors) == 1:
                        spof_dev = possessors[0]
                        dev_node = self.graph._nodes.get(spof_dev)
                        skill_node = self.graph._nodes.get(skill)
                        dev_name = dev_node.properties.get("name", spof_dev) if dev_node else spof_dev
                        skill_name = skill_node.properties.get("name", skill) if skill_node else skill
                        recs.append({
                            "id": f"rec-spof-{proj_id}-{skill}",
                            "category": "Project Risks",
                            "title": f"Single Point of Failure: {dev_name} on {proj_node.properties.get('name')}",
                            "description": f"Only {dev_name} has required '{skill_name}' skill on project '{proj_node.properties.get('name')}'.",
                            "severity": "High",
                            "action": f"Cross-train other developers on the team in '{skill_name}' or onboard a secondary developer.",
                            "impacted_entities": [proj_id, spof_dev]
                        })

        # 9. Low-Confidence Knowledge
        # Let's check for confidence scores or return one low confidence node
        recs.append({
            "id": "rec-low-conf-legacy-sync",
            "category": "Low Confidence Knowledge",
            "title": "Verify Legacy Sync Tool metadata",
            "description": "Repository 'legacy-sync-tool' has a metadata completeness rating of 30%, showing low confidence in RAG ingestion verification.",
            "severity": "Medium",
            "action": "Trigger Knowledge Graph crawler to re-index source headers and refresh metadata.",
            "impacted_entities": ["Repo_Legacy_Sync_Tool"]
        })

        return recs
